/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.stnetix.ariaddna.restapiserver.api;

import com.stnetix.ariaddna.restapiserver.model.ErrorModel;
import com.stnetix.ariaddna.restapiserver.model.StatisticSet;
import java.util.UUID;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-07-24T10:27:06.657+03:00")

@Api(value = "stat", description = "the stat API")
public interface StatApi {

    @ApiOperation(value = "", notes = "Allows to get statistic object about clouds.", response = StatisticSet.class, tags={ "Ariaddna", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Clouds statistic.", response = StatisticSet.class),
        @ApiResponse(code = 404, message = "Bad cloud UUID.", response = ErrorModel.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = ErrorModel.class) })
    
    @RequestMapping(value = "/stat/vufs/{userUuid}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<StatisticSet> getCloudStatisticSet(@ApiParam(value = "User UUID.",required=true ) @PathVariable("userUuid") UUID userUuid);


    @ApiOperation(value = "", notes = "Allows to get health-check statistic about users Clouds.", response = StatisticSet.class, tags={ "Ariaddna", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Clouds health-check statistic.", response = StatisticSet.class),
        @ApiResponse(code = 404, message = "Bad user UUID.", response = ErrorModel.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = ErrorModel.class) })
    
    @RequestMapping(value = "/stat/vufs/health/{userUuid}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<StatisticSet> getHealthCheckStat(@ApiParam(value = "User UUID.",required=true ) @PathVariable("userUuid") UUID userUuid);


    @ApiOperation(value = "", notes = "Allows to post statistic from client to server about clouds.", response = Void.class, tags={ "Ariaddna", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Statistics was send to server.", response = Void.class),
        @ApiResponse(code = 200, message = "Unexpected error.", response = ErrorModel.class) })
    
    @RequestMapping(value = "/stat/vufs/{userUuid}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> postCloudStatSet(@ApiParam(value = "User UUID.",required=true ) @PathVariable("userUuid") UUID userUuid,@ApiParam(value = "Cloud statistic set typed object." ,required=true )  @Valid @RequestBody StatisticSet cloudStatisticSet);

}
